### ISSUE TITLE
Shopp 1.3.8 - 1.3.9dev don't toggle payment buttons at checkout

### ISSUE THREAD

**Issue by mcary** [ingenesis/shopp#3260]
One the checkout page, the latest published plugin version, 1.3.8, and the current development version, 1.3.9dev, don't toggle the payment button between "Submit Order" and "PayPal check out" when selecting the payment option:

> ![image](https://cloud.githubusercontent.com/assets/24826/6681131/9a715cb2-cc1e-11e4-8bc6-d9ea25c32520.png)

On 1.2.5, when a buyer selected a different payment method (Paypal, Offline, etc), the order submission button changed accordingly.

**Comment by crunnells** [comment]
It's more likely you have a JS conflict with another plugin.  This functionality works fine on all of my installs of 1.3.8 and 1.3.9dev, and I haven't seen any other reports of this being a problem.

**Comment by jonathandavis** [comment]
Check the browser console for errors that may be interfering with Shopp's scripted behaviors.

**Comment by mcary** [comment]
Looking at the console, I saw this error: Uncaught TypeError: undefined is not a function

To get the location, I had to enable SCRIPT_DEBUG.  That revealed the issue was inside an unrelated function, quickSelects, defined in core/ui/behaviors/shopp.js, where it calls jQuery(...).on.  The jQuery.on function was added in 1.7, but we are running 1.4.2 from the meshable theme.

A short-term work around to resolve the toggling of payment buttons is to stub jQuery.on:
```Javascript
jQuery.prototype.on = function () {
  return this;
};
```

This also resolved an issue where required options were not enforced when adding to cart.

We'll look into upgrading jQuery in the future.
